# Generated by Django 3.2.3 on 2021-05-28 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_tablereservation_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablereservation',
            name='type',
        ),
        migrations.AddField(
            model_name='tablereservation',
            name='type',
            field=models.ManyToManyField(to='restaurant.Reservation'),
        ),
    ]
