# Generated by Django 3.2.3 on 2021-05-28 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_auto_20210528_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablereservation',
            name='type',
        ),
        migrations.AddField(
            model_name='tablereservation',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.reservation'),
        ),
    ]
