# Generated by Django 3.2.3 on 2021-05-29 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_auto_20210528_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablereservation',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
