# Generated by Django 3.2.3 on 2021-05-29 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_tablereservation_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recreation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('price', models.FloatField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Recreationn',
        ),
    ]
