# Generated by Django 3.2.3 on 2021-05-29 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurant', '0006_auto_20210529_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('price', models.FloatField(null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='recreation',
            old_name='name',
            new_name='email',
        ),
        migrations.AddField(
            model_name='recreation',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.reservation'),
        ),
        migrations.AddField(
            model_name='recreation',
            name='comment',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='recreation',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recreation',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='recreation',
            name='is_paid',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='recreation',
            name='no_people',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='recreation',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
