# Generated by Django 3.2.3 on 2021-06-07 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_auto_20210529_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='picture',
            field=models.ImageField(default='default.jpg', upload_to='images/recreations/'),
        ),
        migrations.AddField(
            model_name='recreation',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
