# Generated by Django 3.2.3 on 2021-06-07 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_rename_no_people_recreation_no_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recreation',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.activity'),
        ),
    ]
