# Generated by Django 3.2.3 on 2021-06-08 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_alter_recreation_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_delivered',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='recreation',
            name='is_approved',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='tablereservation',
            name='is_approved',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
