# Generated by Django 3.2.3 on 2021-06-08 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0011_auto_20210608_0136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablereservation',
            name='name',
        ),
    ]
