# Generated by Django 3.2.4 on 2021-06-29 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0012_remove_tablereservation_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name_plural': 'Activities'},
        ),
    ]
